version: 2.1

orbs:
  python: circleci/python@1.0.0

jobs:
  clean:
    executor: python/default
    steps:
      - run:
          command: |
            make clean-build
          name: Clean
  build:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          args: '-r requirements.txt'
          pkg-manager: pip
      - python/install-packages:
          args: '-r requirements_dev.txt'
          pkg-manager: pip
      - run:
          command: |
            make lint
            make test
          name: Test
      - python/dist
  publish:
    executor: python/default
    steps:
      - checkout
      - python/dist
      - run: make release

workflows:
  main:
    jobs:
      - clean
      - build
